### ISSUE TITLE
AttributeError: interp_param

### ISSUE THREAD

**Issue by kylezlj** [lzx1413/CAFFE_SSD#10]
Hello, I have some problems when use fssd_pascal.py   Maybe you can solve it easily. Thank you very much.

zhaoleijie@weco:~/ssd/caffe$ python ./fssd_pascal.py
Traceback (most recent call last):
  File "./fssd_pascal.py", line 464, in <module>
    print(net.to_proto(), file=f)
  File "/home/zhaoleijie/ssd/caffe/python/caffe/net_spec.py", line 209, in to_proto
    top._to_proto(layers, names, autonames)
  File "/home/zhaoleijie/ssd/caffe/python/caffe/net_spec.py", line 100, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/home/zhaoleijie/ssd/caffe/python/caffe/net_spec.py", line 158, in _to_proto
    assign_proto(layer, k, v)
  File "/home/zhaoleijie/ssd/caffe/python/caffe/net_spec.py", line 64, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: interp_param

@lzx1413

**Comment by zyinggit** [comment]
> 
> 
> 
> Hello,I meet the same problem.when use fssd_pascal.py Maybe you can solve it easily. Thank you very much.
> zhaoleijie@weco:~/ssd/caffe$ python ./fssd_pascal.py
> Traceback (most recent call last):
> File "./fssd_pascal.py", line 464, in
> print(net.to_proto(), file=f)
> File "/home/zhaoleijie/ssd/caffe/python/caffe/net_spec.py", line 209, in to_proto
> top._to_proto(layers, names, autonames)
> File "/home/zhaoleijie/ssd/caffe/python/caffe/net_spec.py", line 100, in _to_proto
> return self.fn._to_proto(layers, names, autonames)
> File "/home/zhaoleijie/ssd/caffe/python/caffe/net_spec.py", line 158, in _to_proto
> assign_proto(layer, k, v)
> File "/home/zhaoleijie/ssd/caffe/python/caffe/net_spec.py", line 64, in assign_proto
> is_repeated_field = hasattr(getattr(proto, name), 'extend')
> AttributeError: interp_param
> 
> @lzx1413
